const themes = [
  "3024-day",
  "3024-night",
  "abcdef",
  "ambiance-mobile",
  "ambiance",
  "ayu-dark",
  "ayu-mirage",
  "base16-dark",
  "base16-light",
  "bespin",
  "blackboard",
  "cobalt",
  "colorforth",
  "darcula",
  "dracula",
  "duotone-dark",
  "duotone-light",
  "eclipse",
  "elegant",
  "erlang-dark",
  "gruvbox-dark",
  "hopscotch",
  "icecoder",
  "idea",
  "isotope",
  "lesser-dark",
  "liquibyte",
  "lucario",

  "material",
  "mbo",
  "mdn-like",
  "midnight",
  "monokai",
  "moxer",
  "neat",
  "neo",
  "night",
  "nord",
  "oceanic-next",
  "panda-syntax",
  "paraiso-dark",
  "paraiso-light",
  "pastel-on-dark",
  "railscasts",
  "seti",
  "shadowfox",
  "solarized",
  "ssms",
  "the-matrix",
  "tomorrow-night-bright",
  "tomorrow-night-eighties",
  "ttcn",
  "yeti",
  "yonce",
  "zenburn",
];

const fonts = [
  "Cairo-Regular",
  "ComicNeue-Light",
  "CourierPrime-Regular",
  "Flamenco-Light",
  "GloriaHallelujah-Regular",
  "LexendPeta-Regular",
  "Nunito-Regular",
  "PatrickHand-Regular",
  "PermanentMarker-Regular",
  "Roboto-Thin",
];
var browserstoragenames = {
  Code: "BrowserCodeStorage@123forWebCodeEditor$!@",
  Font: "BrowserFontStorage@123forWebCodeEditor$!@",
  Theme: "BrowserThemeStorage@123forWebCodeEditor$!@",
};
function setStorageName(__key, __value) {
  browserstoragenames[__key] = __value;
}
function getStorageName(__key) {
  return browserstoragenames[__key];
}
